services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      DB_USERNAME: ${MONGO_USERNAME:-tech}
      DB_PASSWORD: ${MONGO_PASSWORD:-tech_passwd}
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongod", "--version" ]
      interval: 30s
      retries: 3

  fiapfastfood:
    container_name: fiap-fast-food
    build:
      context: .
    image: fiap_fast_food_app/fastfoodapp
    ports:
      - "8080:8080"
    networks:
      - fiaptechchallengenetwork
    depends_on:
      mongo:
        condition: service_healthy

networks:
  fiaptechchallengenetwork:
    name: fiaptechchallengenetwork
    driver: bridge