spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: tech-challenge
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: tech-challenge
        enable_lazy_load_no_trans: true
    show-sql: false
  flyway:
    schemas: tech-challenge

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html
