spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: order-microservice
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME:masteruser}:${DB_PASSWORD:M45t3rp455}@${DB_HOST:fiap-cluster.sfj5d.mongodb.net}/order_db

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

feign:
  client:
    customer:
      url: ${CUSTOMER_HOST:a338d2404287143f3854ba9c6c73072c-1301695279.us-east-1.elb.amazonaws.com}
    item:
      url: ${PRODUCT_HOST:a338d2404287143f3854ba9c6c73072c-1301695279.us-east-1.elb.amazonaws.com}

aws:
  sqs:
    production_order_requests_queue: production_order_requests_queue
    order-payment-updates-queue: order-payment-updates-queue
    payment-requests-queue: payment-requests-queue
