spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: order-microservice
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/order_db

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

feign:
  client:
    customer:
      url: ${CUSTOMER_HOST}
    item:
      url: ${PRODUCT_HOST}

aws:
  sqs:
    production_order_requests_queue: production_order_requests_queue
    order-payment-updates-queue: order-payment-updates-queue
    payment-requests-queue: payment-requests-queue
