spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: order-microservice
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:27017/order-microservice
      database: order-microservice

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

feign:
  client:
    customer:
      url: http://localhost:8080
    item:
      url: http://localhost:8080

aws:
  sqs:
    production_order_requests_queue: production_order_requests_queue
    order-payment-updates-queue: order-payment-updates-queue
    payment-requests-queue: payment-requests-queue